### ISSUE TITLE
Mi Band 2 support

### ISSUE THREAD

**Issue by lindevs** [Iyeonghun/Mi_Band_SDK#1]
Hi, did this library support Mi Band 2 ?

**Comment by Iyeonghun** [comment]
Hi, I couldn't work because I was too busy now.
But if I start to develop it, I think I'll be able to apply it immediately.
I think I'll be free around 10 February.
Sorry for not being able to help.

**Comment by Jay268** [comment]
@Iyeonghun Did you able to setup support for Miband2 as it is not working with that. Could you please have a look into it if you can add support for Miband2 it will be great.
